export type colorName = keyof typeof colorClasses | undefined;

export const colorClasses = {
	red: { bg: "bg-red-400", text: "text-red-900" },
	green: { bg: "bg-green-400", text: "text-green-900" },
	blue: { bg: "bg-blue-400", text: "text-blue-900" },
	yellow: { bg: "bg-yellow-400", text: "text-yellow-900" },
	purple: { bg: "bg-purple-400", text: "text-purple-900" },
	pink: { bg: "bg-pink-400", text: "text-pink-900" },
	indigo: { bg: "bg-indigo-400", text: "text-indigo-900" },
	teal: { bg: "bg-teal-400", text: "text-teal-900" },
	cyan: { bg: "bg-cyan-400", text: "text-cyan-900" },
	orange: { bg: "bg-orange-400", text: "text-orange-900" },
	lime: { bg: "bg-lime-400", text: "text-lime-900" },
	emerald: { bg: "bg-emerald-400", text: "text-emerald-900" },
	rose: { bg: "bg-rose-400", text: "text-rose-900" },
	violet: { bg: "bg-violet-400", text: "text-violet-900" },
	fuchsia: { bg: "bg-fuchsia-400", text: "text-fuchsia-900" },
	sky: { bg: "bg-sky-400", text: "text-sky-900" },
	slate: { bg: "bg-slate-400", text: "text-slate-900" },
	zinc: { bg: "bg-zinc-400", text: "text-zinc-900" },
	neutral: { bg: "bg-neutral-400", text: "text-neutral-900" },
	stone: { bg: "bg-stone-400", text: "text-stone-900" },
	amber: { bg: "bg-amber-400", text: "text-amber-900" },
	gray: { bg: "bg-gray-400", text: "text-gray-900" },
	cool: { bg: "bg-cool-gray-400", text: "text-cool-gray-900" },
	warm: { bg: "bg-warm-gray-400", text: "text-warm-gray-900" },
	prussian: { bg: "bg-prussian-400", text: "text-prussian-900" },
	magenta: { bg: "bg-pink-500", text: "text-pink-950" },
	mint: { bg: "bg-teal-300", text: "text-teal-800" },
	charcoal: { bg: "bg-gray-700", text: "text-gray-100" },
	gold: { bg: "bg-yellow-500", text: "text-yellow-950" },
	bronze: { bg: "bg-orange-600", text: "text-orange-100" },
} as const;
